language: node_js
node_js: '12'
branches:
  only:
  - master
  - /^greenkeeper/.*$/
  - /^renovate/.*$/
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  verbose: true
  on:
    branch: master
